---


# - name: Add Elasticsearch RPM repository
#   yum_repository:
#     name: elasticsearch
#     description: Elasticsearch Repository
#     baseurl: https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/yum
#     gpgcheck: yes
#     gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
#     enabled: yes


# sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch


# [elastic-8.x]
# name=Elastic repository for 8.x packages
# baseurl=https://artifacts.elastic.co/packages/8.x/yum
# gpgcheck=1
# gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
# enabled=1
# autorefresh=1
# type=rpm-md


# baseurl=https://artifacts.elastic.co/packages/oss-8.x/yum
#----------------------------
# wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
#sudo apt-get install apt-transport-https
# echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list
# sudo apt-get update && sudo apt-get install kibana
#--------------------
#Details:
#Install ELK on Ubuntu server
#lsb_release -a
#sudo apt install default-jdk default-jre -y 
#javac -version 
#curl -fsSL https://artifacts.elastic.co/GPG-KEY-... |sudo gpg --dearmor -o /usr/share/keyrings/elastic.gpg
#echo "deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages... stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
#sudo apt update 
#sudo  apt install elasticsearch -y 
#sudo vim /etc/elasticsearch/elasticsearch.yml 
#network.host: localhost
#http.port: 9200

#sudo vim /etc/elasticsearch/jvm.options
#-Xms512m
#-Xmx512m
#sudo systemctl restart elasticsearch 
#sudo systemctl enable elasticsearch 
#curl -X GET "localhost:9200"
#curl -X GET "http://localhost:9200" -u elastic:pass
#sudo  apt install logstash -y
#sudo  systemctl start logstash 
# sudo systemctl enable logstash
#sudo systemctl status logstash 
#sudo apt install kibana -y
#sudo vim /etc/kibana/kibana.yml 
#server.port: 5601
#server.host: "localhost"
#elasticsearch.hosts: ["http://localhost:9200"]
#sudo systemctl start kibana 
#sudo  systemctl enable kibana 
#sudo systemctl status kibana 
# http://localhost:9200
#sudo apt install filebeat
#sudo filebeat modules enable system
#sudo systemctl start filebeat
